name: Bug report
description: Report a reproducible problem
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect instead?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: ssg version
      placeholder: "bash bin/ssg --version"
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: "OS, systemd version (systemctl --version)"
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: "journalctl output, CI logs"
