name: Feature request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What pain does this solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: How should it work?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
