name: Release
on:
  push:
    tags: ["v*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make tarball
        run: |
          mkdir -p dist
          tar -czf dist/systemd-service-generator-${GITHUB_REF_NAME}.tar.gz bin lib steps README.md LICENSE VERSION
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-asset
          path: dist/*.tar.gz
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-asset
          path: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
